const ACCOUNT = {
  // SIGNUP
  SIGNING_UP: 'ACCOUNT_SIGNING_UP',
  SIGNUP_UNSUCCESS: 'ACCOUNT_SIGNUP_UNSUCCESS',
  SIGNUP_SUCCESS: 'ACCOUNT_SIGNUP_SUCCESS',
  // LOGIN
  LOGING_IN: 'ACCOUNT_LOGING_IN',
  LOGIN_ERROR: 'ACCOUNT_LOGIN_ERROR',
  LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
  LOGIN_UNSUCCESS: 'ACCOUNT_LOGIN_UNSUCCESS',
  // LOAD
  LOADING: 'ACCOUNT_LOADING',
  LOADED: 'ACCOUNT_LOADED',
  // LOGOUT
  LOGOUT: 'ACCOUNT_LOGOUT',
  // UPDATE
  UPDATE: 'ACCOUNT_UPDATE',
};
export {
  ACCOUNT,
};
