const ACCOUNT = {
  // SIGNUP
  SIGNUP_START: 'ACCOUNT_SIGNUP_START',
  SIGNUP_SUCCESS: 'ACCOUNT_SIGNUP_SUCCESS',
  SIGNUP_UNSUCCESS: 'ACCOUNT_SIGNUP_UNSUCCESS',
  SIGNUP_ERROR: 'ACCOUNT_SIGNUP_ERROR',
  // LOGIN
  LOGIN_START: 'ACCOUNT_LOGIN_START',
  LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
  LOGIN_UNSUCCESS: 'ACCOUNT_LOGIN_UNSUCCESS',
  LOGIN_ERROR: 'ACCOUNT_LOGIN_ERROR',
  // LOGOUT
  LOGOUT: 'ACCOUNT_LOGOUT',
};
export {
  ACCOUNT
};
